# Generated by Django 5.1.6 on 2025-04-13 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Tekst komentara')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Kada je komentar kreiran')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Kada je komentar zadnji put ažuriran')),
                ('blog', models.ForeignKey(help_text='Blog post na koji se komentar odnosi. Uzimamo slug iz Blog modela preko veze.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog')),
                ('parent', models.ForeignKey(blank=True, help_text='Ako je postavljen, označava da je ovaj komentar odgovor na drugi komentar.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comment.comment')),
                ('user', models.ForeignKey(help_text='Korisnik koji je napisao komentar.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Komentar',
                'verbose_name_plural': 'Komentari',
                'ordering': ['created_at'],
            },
        ),
    ]
