# Generated by Django 5.1.6 on 2025-04-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Komentar', 'verbose_name_plural': 'Komentari'},
        ),
    ]
